server:
  port: 80

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false    #false代表不像注册中心注册自己
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:70013/eureka/  #设置与Eureka server交互式的地址查询服务和注册服务都需要依赖这个地址


