server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001 #eureka服务端的实例名称   单机配置  hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false代表不像注册中心注册自己
    fetch-registry: false   #false表示本端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url: #单机配置  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka server交互式的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/